// src/App.tsx
import React from 'react'

function App() {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center">
      <div className="bg-white p-8 rounded-lg shadow-md">
        <h1 className="text-2xl font-bold text-gray-800">Welcome to Vite + React!</h1>
      </div>
    </div>
  )
}

export default App

// src/App.vue
<script setup lang="ts">
import VideoCall from './components/VideoCall.vue'
</script>

<template>
  <div class="min-h-screen bg-gray-100">
    <header class="bg-white shadow">
      <div class="max-w-7xl mx-auto py-6 px-4">
        <h1 class="text-3xl font-bold text-gray-900">WebRTC Video Chat</h1>
      </div>
    </header>
    <main>
      <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <VideoCall />
      </div>
    </main>
  </div>
</template>
